### PR TITLE
Pass child snapshot instead of child object to forEach fn

### PR DESCRIPTION
**Pull request by benadamstyles**
This matches the Firebase Web SDK behaviour.

### CODE REVIEW

**Comment by benadamstyles** [comment]
Should I have added unit tests for this? Happy to.

**Comment by Ehesp** [comment]
It's just @Salakar being lazy. He'll reply tomorrow haha

**Comment by Salakar** [comment]
Sssh @Ehesp ;p

**Comment by benadamstyles** [comment]
Thanks for merging this btw. Just wondered where is the best place to discuss ideas/questions I have about this fork? Would usually use the repo issues for that. I'm going to be using this fork heavily over the next few weeks/months so hopefully I will have some contributions to make and it would be great to be able to discuss things with all you guys that are involved in it without having to submit a PR!

**Pull request merged**
