### PR TITLE
Allow Java database module to deal with Array data types

### PR DESCRIPTION
**Pull request by chrisbianca**
Currently there is a disparity between the way that Android and iOS deal with Array like data types returned by Firebase.

This brings Java inline with iOS by returning Array types as an Array rather than a Map.

Also cleaned up the unused method that existed in FirebaseDatabase to make it clear where this functionality was being performed.

### CODE REVIEW

**Comment by Salakar** [comment]
Looking good, do you know what the web api returns them as? Is it map or an array?

**Comment by chrisbianca** [comment]
I haven't tested myself, but based on this [blog post](https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html), I would assume that it's arrays.

The iOS code that resolves the data to an array is internal to Firebase, so this would imply a list is the correct data type.  It would also not be easily possible to change the iOS code to resolve a map instead.

**Comment by Salakar** [comment]
Cool, merging! Thanks for this

**Comment by auser** [comment]
:)!

**Pull request merged**
